# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f8949e15d4abacecff3574d628d54d4eb27591f51bf110a4309dc31381fa5c275ab6edbf1b6c6b7c480d5f823260e51f97c89ddbab2dd772a240b31d027fee0

test:
  secret_key_base: a6fc4764845d98c4bb4ccba4254266d96a920be3f7d9531f3d9ad010449fb9607cd334a2eca3a182798dc4d20f9797f59f1c285447acbefe26b2f2755c10b182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
