# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5af1898eb719d5381d15c03885e17acc2ae8b63bec5fa9d75d966a562f3f70b7a54c476d0b180364554ffa50cb74a58aae25fdc32f048ed6da06939f2ecac45

test:
  secret_key_base: 464f5fc8a17e818d16e51da92690b181bb5f0fcd87a00d7e4fbcac9c75348d194246e2c3b1316054a1f2c1bbf7cdf24226f57a683cd792692ce118ee746bfdde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
